@extends('layout.template')

@section('content')
<table class="table table-striped">
    <thead>
        <tr>
            <th>No</th>
            <th>Nama</th>
            <th>NIM</th>
            <th>Kelas</th>
        </tr>
    </thead>
    <tbody>
        <tr>
                <td>1</td>
                <td>Rezky</td>
                <td>513284</td>
                <td>A</td>
        </tr>
        <tr>
                <td>2</td>
                <td>Meiva</td>
                <td>513284</td>
                <td>A</td>
        </tr>
        <tr>
                <td>3</td>
                <td>Anisa</td>
                <td>513284</td>
                <td>A</td>
        </tr>
        <tr>
                <td>4</td>
                <td>Alim</td>
                <td>514254</td>
                <td>A</td>
        </tr>
    </tbody>
</table>
@endsection
